# HTTP server - Chuyển hướng sang HTTPS
server {
    listen 80;
    server_name ddd-laravel.local;

    # Chuyển hướng HTTP sang HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS server - Sử dụng chứng chỉ tự ký
server {
    listen 443 ssl;
    server_name ddd-laravel.local;

    # Cấu hình SSL
    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;

    root /var/www/html/repo/public;

    index index.php index.html;

    # Xử lý yêu cầu chính
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Xử lý PHP
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass ddd-laravel:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Từ chối truy cập file .ht
    location ~ /\.ht {
        deny all;
    }
}
